my_work
Slava-11/JS-learn pull request #1
Opened 2022-10-05 14:11 UTC by Slava-11

2022-10-05 20:17 UTC, mikerudenko requested changes

2022-10-05 20:17 UTC, mikerudenko commented on web/2022/Gondor/src/scss/index.scss
> +body{
розбити на декілька файлів - header.scss, main.scss, footer.scss

2022-10-05 20:17 UTC, mikerudenko commented on web/2022/Gondor/src/scss/index.scss
> +.header{
code is not formatted, please format code before push

2022-10-05 20:17 UTC, mikerudenko commented on web/2022/Gondor/src/scss/index.scss
> +        li{
you should use only class selectors, selectors by tag are bad practise

2022-10-05 20:17 UTC, mikerudenko commented on web/2022/Gondor/src/scss/index.scss
> +    @keyframes circle{
please create separate file animation.scss

2022-10-05 20:17 UTC, mikerudenko commented on web/2022/Gondor/src/index.html
> +                <ul>
please add class to tags - ul and li

2022-10-05 20:17 UTC, mikerudenko commented on web/2022/Gondor/src/index.html
> +    <div class="header">
please format html

2022-10-05 20:17 UTC, mikerudenko commented on web/2022/Gondor/src/index.html
> +        <div class="header_flex">
classes should naming with understandable meaning

2022-10-05 20:17 UTC, mikerudenko commented on web/2022/Gondor/src/index.html
> +        <div class="header_flex">
you should NOT use css in class names

2022-10-05 20:17 UTC, mikerudenko commented on web/2022/Gondor/src/index.html
> +            <div class="header_flex_circle"><img class="circle_img1" src="img/img1.jpg.crdownload" alt=""/></div>
please rename all your images

2022-10-05 20:17 UTC, mikerudenko commented on web/2022/Gondor/src/index.html
> +    <div class="nav2">
nav1, nav2, nav3 are bad namings - please use meaning classes like

Google name - minas-tirith-section, aragorm-section, footer-section

2022-10-07 15:08 UTC, Slava-11 commented
understood accepted processed

2022-10-08 21:46 UTC, mikerudenko approved these changes

2022-10-08 21:48 UTC, merged